<?php
$title='Kelola Data';require 'header.php';
$config=[
'posts'=>['label'=>'Berita','table'=>'posts','fields'=>['judul'=>'Judul','kategori'=>'Kategori','isi'=>'Isi','status'=>'Status','tanggal'=>'Tanggal','gambar'=>'Foto']],
'announcements'=>['label'=>'Pengumuman','table'=>'announcements','fields'=>['judul'=>'Judul','isi'=>'Isi','tanggal'=>'Tanggal','status'=>'Status']],
'activities'=>['label'=>'Kegiatan','table'=>'activities','fields'=>['nama'=>'Nama Kegiatan','pj'=>'PJ','kontak'=>'Kontak PJ','pic'=>'PIC Kegiatan','waktu'=>'Waktu','tempat'=>'Tempat','alat_bahan'=>'Alat & Bahan','detail'=>'Detail Kegiatan','luaran'=>'Luaran/Hasil','status'=>'Status','gambar'=>'Foto']],
'potentials'=>['label'=>'Potensi Desa','table'=>'potentials','fields'=>['nama'=>'Nama Potensi','kategori'=>'Kategori','deskripsi'=>'Deskripsi','lokasi'=>'Lokasi','pengelola'=>'Pengelola','kontak'=>'Kontak','gambar'=>'Foto']],
'umkm'=>['label'=>'UMKM & Produk','table'=>'umkm','fields'=>['nama_produk'=>'Nama Produk','pemilik'=>'Pemilik','kategori'=>'Kategori','harga'=>'Harga','deskripsi'=>'Deskripsi','kontak'=>'Kontak','lokasi'=>'Lokasi','gambar'=>'Foto']],
'documents'=>['label'=>'Dokumen','table'=>'documents','fields'=>['judul'=>'Judul','kategori'=>'Kategori','tanggal'=>'Tanggal','deskripsi'=>'Deskripsi','file_path'=>'File PDF']],
'galleries'=>['label'=>'Galeri','table'=>'galleries','fields'=>['judul'=>'Judul','tanggal'=>'Tanggal','gambar'=>'Foto','kategori'=>'Kategori']],
'services'=>['label'=>'Pelayanan','table'=>'services','fields'=>['nama'=>'Nama Layanan','persyaratan'=>'Persyaratan','prosedur'=>'Prosedur','keterangan'=>'Keterangan','status'=>'Aktif (1/0)']],
'complaints'=>['label'=>'Pengaduan','table'=>'complaints','fields'=>['nama'=>'Nama','kontak'=>'Kontak','kategori'=>'Kategori','isi'=>'Isi','status'=>'Status']]
];
$type=$_GET['type']??'posts';if(!isset($config[$type])){$type='posts';}$cfg=$config[$type];$table=$cfg['table'];$edit=null;
if(isset($_GET['delete']) && $type!=='complaints'){ $id=(int)$_GET['delete'];$pdo->prepare("DELETE FROM $table WHERE id=?")->execute([$id]);flash('ok','Data berhasil dihapus.');header("Location: manage.php?type=$type");exit;}
if(isset($_GET['edit'])){$st=$pdo->prepare("SELECT * FROM $table WHERE id=?");$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $id=(int)($_POST['id']??0);$data=[];
 foreach($cfg['fields'] as $field=>$label){if(in_array($field,['gambar','file_path']))continue;$data[$field]=trim($_POST[$field]??'');}
 if(isset($cfg['fields']['gambar'])){$up=upload_file('gambar','uploads',['jpg','jpeg','png','webp']);if($up)$data['gambar']=$up;else if($edit)$data['gambar']=$edit['gambar']??null;}
 if(isset($cfg['fields']['file_path'])){$up=upload_file('file_path','uploads',['pdf','doc','docx','xls','xlsx']);if($up)$data['file_path']=$up;else if($edit)$data['file_path']=$edit['file_path']??null;}
 if($id){$sets=[];$vals=[];foreach($data as $k=>$v){$sets[]="$k=?";$vals[]=$v;}$vals[]=$id;$pdo->prepare("UPDATE $table SET ".implode(',',$sets)." WHERE id=?")->execute($vals);flash('ok','Data berhasil diperbarui.');}
 else{$cols=array_keys($data);$pdo->prepare("INSERT INTO $table (".implode(',',$cols).") VALUES (".implode(',',array_fill(0,count($cols),'?')).")")->execute(array_values($data));flash('ok','Data berhasil ditambahkan.');}
 header("Location: manage.php?type=$type");exit;
}
$rows=$pdo->query("SELECT * FROM $table ORDER BY id DESC")->fetchAll();$ok=flash('ok');
function field_input($f,$label,$value){$ta=in_array($f,['isi','deskripsi','alat_bahan','detail','luaran','persyaratan','prosedur','keterangan']);$date=$f==='tanggal';if($f==='status'){return '<select name="status" class="form-select"><option value="publish">Publish</option><option value="draft">Draft</option><option value="aktif">Aktif</option><option value="arsip">Arsip</option><option value="direncanakan">Direncanakan</option><option value="berlangsung">Berlangsung</option><option value="selesai">Selesai</option><option value="diterima">Diterima</option><option value="diproses">Diproses</option></select>';} if($f==='gambar'||$f==='file_path')return '<input type="file" name="'.e($f).'" class="form-control">';return $ta?'<textarea name="'.e($f).'" class="form-control" rows="4">'.e($value).'</textarea>':'<input name="'.e($f).'" type="'.($date?'date':'text').'" class="form-control" value="'.e($value).'">';}
?><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold"><?=e($cfg['label'])?></h2><p class="text-muted mb-0">Tambah, edit, dan hapus data.</p></div><?php if($type!=='complaints'):?><a href="manage.php?type=<?=$type?>&new=1" class="btn btn-primary">+ Tambah Data</a><?php endif;?></div><?php if($ok):?><div class="alert alert-success"><?=e($ok)?></div><?php endif;?>
<?php if(isset($_GET['new'])||$edit):?><div class="card card-soft p-4 mb-4"><h5><?=($edit?'Edit':'Tambah')?> <?=$cfg['label']?></h5><form method="post" enctype="multipart/form-data"><input type="hidden" name="id" value="<?=e($edit['id']??0)?>"><div class="row g-3"><?php foreach($cfg['fields'] as $f=>$label):?><div class="col-md-<?=in_array($f,['isi','deskripsi','alat_bahan','detail','luaran','persyaratan','prosedur','keterangan'])?'12':'6'?>"><label class="form-label"><?=e($label)?></label><?=field_input($f,$label,$edit[$f]??($f==='tanggal'?date('Y-m-d'):''))?><?php if($edit && in_array($f,['gambar','file_path'])&&$edit[$f]):?><small class="text-muted">File saat ini: <?=e($edit[$f])?></small><?php endif;?></div><?php endforeach;?></div><button class="btn btn-primary mt-3">Simpan</button> <a href="manage.php?type=<?=$type?>" class="btn btn-light mt-3">Batal</a></form></div><?php endif;?>
<div class="card card-soft p-3"><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><?php foreach(array_slice($cfg['fields'],0,4,true) as $label):?><th><?=e($label)?></th><?php endforeach;?><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=$r['id']?></td><?php $shown=0;foreach($cfg['fields'] as $f=>$label){if($shown>=4)break;$v=$r[$f]??'';echo '<td>'.e(mb_substr(strip_tags((string)$v),0,60)).'</td>';$shown++;} ?><td><?php if($type!=='complaints'):?><a href="manage.php?type=<?=$type?>&edit=<?=$r['id']?>" class="btn btn-sm btn-outline-primary">Edit</a> <a onclick="return confirm('Hapus data ini?')" href="manage.php?type=<?=$type?>&delete=<?=$r['id']?>" class="btn btn-sm btn-outline-danger">Hapus</a><?php else:?><a href="manage.php?type=complaints&edit=<?=$r['id']?>" class="btn btn-sm btn-outline-primary">Proses</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div><?php require 'footer.php'; ?>
